$('#info').on('click', function(){
  $().msgpopup({
   time: false,
    text: "  <div class='head'>At-Tahrim (Mengharamkan)</div><div class='cont'><hr> <b>Surat At Tahrim:</b> Surat ini terdiri atas 12 ayat, termasuk golongan surat-surat Madaniyyah, diturunkan sesudah surat Al Hujuraat. Dinamai surat <i>At Tahrim</i> karena pada awal surat ini terdapat kata <i>tuharrim</i> yang kata asalnya adalah Attahrim yang berarti <i>mengharamkan</i>.<br><br> Pokok-pokok isinya :<br><br><i>1. Keimanan:</i><br> Kesempatan bertaubat itu hanyalah di dunia saja, segala amal perbuatan manusia di dunia akan dibalas di akhirat.<br><br><i>2. Hukum-hukum:</i><br> Larangan mengharamkan apa-apa yang dibolehkan Allah SWT, kewajiban membebaskan diri dari sumpah yang diucapkan untuk mengharamkan yang halal dengan membayar kaffarat; kewajiban memelihara diri dan keluarga dari api neraka; perintah memerangi orang-orang kafir dan munafik dan berlaku keras terhadap mereka di waktu perang.<br><br><i>3. Dan lain-lain:</i><br> Iman dan perbuatan baik atau buruk seseorang tidak tergantung kepada iman dan perbuatan orang lain walaupun antara suami isteri, seperti isteri Nabi Luth AS, isteri Nabi Nuh AS, isteri Fir'aun, dan Maryam.<br><br> </div>  ",    type: 'info'  });})
$('#info-2').on('click', function(){
  $().msgpopup({
   time: false,
    text: "  <div class='head'>At-Tahrim (Mengharamkan)</div><div class='cont'><hr><b>Surat At Tahrim</b> menerangkan tentang hubungan Rasulullah SAW dengan isteri-isterinya, diikuti dengan keharusan bagi orang-orang mukmin untuk bertaubat; dan ditutup dengan contoh-contoh wanita-wanita yang baik dan yang buruk.<br><br><i>HUBUNGAN SURAT AT TAHRIM DENGAN SURAT AL MULK</i><br><br> Dalam surat At Tahrim diterangkan bahwa Allah mengetahui segala rahasia, sedang pada surat Al Mulk ditegaskan lagi bahwa Allah mengetahui segala rahasia karena Allah menguasai seluruh alam.<br><br></div>  ",    type: 'info'  });})
document.getElementById("srt-66").innerHTML = ' <a onClick="return noHistory(this);" href="118.html#1">1</a> <a onClick="return noHistory(this);" href="118.html#2">2</a> <a onClick="return noHistory(this);" href="118.html#3">3</a> <a onClick="return noHistory(this);" href="118.html#4">4</a> <a onClick="return noHistory(this);" href="118.html#5">5</a> <a onClick="return noHistory(this);" href="118.html#6">6</a> <a onClick="return noHistory(this);" href="118.html#7">7</a> <a onClick="return noHistory(this);" href="118.html#8">8</a> <a onClick="return noHistory(this);" href="118.html#9">9</a> <a onClick="return noHistory(this);" href="118.html#10">10</a> <a onClick="return noHistory(this);" href="118.html#11">11</a> <a onClick="return noHistory(this);" href="118.html#12">12</a> </br> </br> ';
