$('#info').on('click', function(){
  $().msgpopup({
   time: false,
    text: "  <div class='head'>Al-Mulk (Kerajaan)</div><div class='cont'><hr><b>Surat Al Mulk:</b> Surat ini terdiri atas 30 ayat, termasuk golongan surat-surat Makkiyah, diturunkan sesudah Ath Thuur.<br> Nama <i>Al Mulk</i> diambil dari kata <i>Al Mulk</i> yang terdapat pada ayat pertama surat ini yang artinya kerajaan atau kekuasaan. Dinamai pula surat ini dengan <i>At Tabaarak</i> (Maha Suci).<br><br> Pokok-pokok isinya:<br> Hidup dan mati ujian bagi manusia; Allah menciptakan langit berlapis-lapis dan semua ciptaan-Nya mempunyai keseimbangan; perintah Allah untuk memperhatikan isi alam semesta; azab yang diancamkan terhadap orang-orang kafir; dan janji Allah kepada orang-orang mukmin; Allah menjadikan bumi sedemikian rupa hingga mudah bagi manusia untuk mencari rezki; peringatan Allah kepada manusia tentang sedikitnya mereka yang bersyukur kepada nikmat Allah.<br><br> </div>  ",    type: 'info'  });})
$('#info-2').on('click', function(){
  $().msgpopup({
   time: false,
    text: "  <div class='head'>Al-Mulk (Kerajaan)</div><div class='cont'><hr><b>Surat Al Mulk</b> menunjukkan bukti-bukti kebesaran dan kekuasaan Allah yang terdapat di alam semesta dan menganjurkannya agar manusia memperhatikannya dengan seksama sehingga mereka beriman kepada-Nya. Bilamana manusia itu tetap mengingkari, Allah akan menjatuhkan azab kepada mereka.<br><br><i>HUBUNGAN SURAT AL MULK DENGAN SURAT AL QALAM</i><br><br> 1. Pada akhir surat Al Mulk, Allah mengancam orang yang tidak bersyukur kepda nikmat Allah dengan mengeringkan bumi atas mereka, sedang dalam surat Al Qalam diberikan contoh tentang azab terhadap orang-orang yang tidak bersyukur terhadap nikmat Allah.<br> 2. Kedua surat ini sama-sama memberikan ancaman kepada orang-orang kafir.<br><br></div>  ",    type: 'info'  });})
document.getElementById("srt-67").innerHTML = ' <a onClick="return noHistory(this);" href="119.html#1">1</a> <a onClick="return noHistory(this);" href="119.html#2">2</a> <a onClick="return noHistory(this);" href="119.html#3">3</a> <a onClick="return noHistory(this);" href="119.html#4">4</a> <a onClick="return noHistory(this);" href="119.html#5">5</a> <a onClick="return noHistory(this);" href="119.html#6">6</a> <a onClick="return noHistory(this);" href="119.html#7">7</a> <a onClick="return noHistory(this);" href="119.html#8">8</a> <a onClick="return noHistory(this);" href="119.html#9">9</a> <a onClick="return noHistory(this);" href="119.html#10">10</a> <a onClick="return noHistory(this);" href="119.html#11">11</a> <a onClick="return noHistory(this);" href="119.html#12">12</a> <a onClick="return noHistory(this);" href="119.html#13">13</a> <a onClick="return noHistory(this);" href="119.html#14">14</a> <a onClick="return noHistory(this);" href="119.html#15">15</a> <a onClick="return noHistory(this);" href="119.html#16">16</a> <a onClick="return noHistory(this);" href="119.html#17">17</a> <a onClick="return noHistory(this);" href="119.html#18">18</a> <a onClick="return noHistory(this);" href="119.html#19">19</a> <a onClick="return noHistory(this);" href="119.html#20">20</a> <a onClick="return noHistory(this);" href="119.html#21">21</a> <a onClick="return noHistory(this);" href="119.html#22">22</a> <a onClick="return noHistory(this);" href="119.html#23">23</a> <a onClick="return noHistory(this);" href="119.html#24">24</a> <a onClick="return noHistory(this);" href="119.html#25">25</a> <a onClick="return noHistory(this);" href="119.html#26">26</a> <a onClick="return noHistory(this);" href="119.html#27">27</a> <a onClick="return noHistory(this);" href="119.html#28">28</a> <a onClick="return noHistory(this);" href="119.html#29">29</a> <a onClick="return noHistory(this);" href="119.html#30">30</a> </br> </br>  ';
 