$('#info').on('click', function(){
  $().msgpopup({
   time: false,
    text: "  <div class='head'>Al-Jinn (Jin)</div><div class='cont'><hr><b>Surat Al Jinn:</b> terdiri atas 28 ayat, termasuk golongan surat-surat Makkiyyah, diturunkan sesudah surat Al A'raaf. Dinamai <i>Al Jin</i> diambil dari perkataan <i>Al Jin</i> yang terdapat pada ayat pertama surat ini. Pada ayat tersebut dan ayat-ayat berikutnya diterangkan bahwa Jin sebagai makhluk halus telah mendengar pembacaan Al Quran dan mereka mengikuti ajaran Al Quran tersebut.<br><br> Pokok-pokok isinya :<br> Pengetahuan tentang jin diperoleh Nabi Muhammad s.a.w. dengan jalan wahyu; pernyataan iman segolongan jin kepada Allah; jin ada yang mukmin ada pula yang kafir; janji Allah kepada jin dan manusia untuk melimpahkan rezki-Nya kalau mereka mengikuti jalan yang lurus; janji perlindungan Allah terhadap Nabi Muhammad s.a.w. dan wahyu yang dibawanya.<br><br> </div>  ",    type: 'info'  });})
$('#info-2').on('click', function(){
  $().msgpopup({
   time: false,
    text: "  <div class='head'>Al-Jinn (Jin)</div><div class='cont'><hr><b>Surat Al Jinn</b> menerangkan bahwa Al Quran di samping petunjuk bagi manusia juga sebagai petunjuk bagi jin.<br><br><i>HUBUNGAN SURAT AL JINN DENGAN SURAT AL MUZZAMMIL</i><br><br> 1. Surat Al Jin menerangkan ketakjuban segolongan jin yang mendengarkan pembacaan Al Quran, sedang pada surat Al Muzzammil Allah memerintahkan Nabi Muhammad s.a.w. membaca Al Quran pada waktu malam.<br> 2. Pada surat Al Jinn diterangkan bahwa orang-orang kafir Mekah selalu mengganggu Nabi Muhammad s.a.w. bila beliau sembahyang sedang surat Al Muzammil memerintahkan agar Nabi Muhammad s.a.w. mengerjakan sembahyang malam untuk menguatkan jiwanya.<br><br></div>  ",    type: 'info'  });})
document.getElementById("srt-72").innerHTML = ' <a onClick="return noHistory(this);" href="124.html#1">1</a> <a onClick="return noHistory(this);" href="124.html#2">2</a> <a onClick="return noHistory(this);" href="124.html#3">3</a> <a onClick="return noHistory(this);" href="124.html#4">4</a> <a onClick="return noHistory(this);" href="124.html#5">5</a> <a onClick="return noHistory(this);" href="124.html#6">6</a> <a onClick="return noHistory(this);" href="124.html#7">7</a> <a onClick="return noHistory(this);" href="124.html#8">8</a> <a onClick="return noHistory(this);" href="124.html#9">9</a> <a onClick="return noHistory(this);" href="124.html#10">10</a> <a onClick="return noHistory(this);" href="124.html#11">11</a> <a onClick="return noHistory(this);" href="124.html#12">12</a> <a onClick="return noHistory(this);" href="124.html#13">13</a> <a onClick="return noHistory(this);" href="124.html#14">14</a> <a onClick="return noHistory(this);" href="124.html#15">15</a> <a onClick="return noHistory(this);" href="124.html#16">16</a> <a onClick="return noHistory(this);" href="124.html#17">17</a> <a onClick="return noHistory(this);" href="124.html#18">18</a> <a onClick="return noHistory(this);" href="124.html#19">19</a> <a onClick="return noHistory(this);" href="124.html#20">20</a> <a onClick="return noHistory(this);" href="124.html#21">21</a> <a onClick="return noHistory(this);" href="124.html#22">22</a> <a onClick="return noHistory(this);" href="124.html#23">23</a> <a onClick="return noHistory(this);" href="124.html#24">24</a> <a onClick="return noHistory(this);" href="124.html#25">25</a> <a onClick="return noHistory(this);" href="124.html#26">26</a> <a onClick="return noHistory(this);" href="124.html#27">27</a> <a onClick="return noHistory(this);" href="124.html#28">28</a> </br> </br> ';
