$('#info').on('click', function(){
  $().msgpopup({
   time: false,
    text: "  <div class='head'>Adh-Dhuha (Waktu Dhuha)</div><div class='cont'><hr><b>Surat Adh Dhuhaa:</b> Surat ini terdiri atas 11 ayat, termasuk golongan surat Makiyyah dan diturunkan sesudah surat Al Fajr. Nama <i>Adh Dhuhaa</i> diambil dari kata yang terdapat pada ayat pertama, artinya : waktu matahari sepenggalahan naik.<br><br><i>Pokok-pokok Isinya:</i><br> Allah s.w.t. sekali-kali tidak akan meninggalkan Nabi Muhammad s.a.w Isyarat dari Allah s.w.t. bahwa kehidupan Nabi Muhammad s.a.w. dan da'wahnya akan bertambah baik dan berkembang; larangan menghina anak yatim dan menghardik orang-orang yang minta-minta dan perintah menyebut-nyebut nikmat yang diberikan Allah sebagai tanda bersyukur.<br><br> </div>  ",    type: 'info'  });})
$('#info-2').on('click', function(){
  $().msgpopup({
   time: false,
    text: "  <div class='head'>Adh-Dhuha (Waktu Dhuha)</div><div class='cont'><hr><b>Surat Adh Dhuhaa:</b> menerangkan tentang bimbingan pemeliharaan Allah s.w.t. terhadap Nabi Muhammad s.a.w. dengan cara yang tak putus-putusnya dan mengandung pula perintah kepada Nabi supaya mensyukuri segala nikmat itu.<br><br><i>HUBUNGAN SURAT ADH DHUHAA DENGAN SURAT ALAM NASYRAH</i><br><br> 1. Kedua surat ini amat erat hubungannya karena sama-sama ditujukan kepada Nabi Muhammad s.a.w.<br> 2. Kedua surat ini sama-sama menerangkan nikmat Allah dan memerintahkan kepada Nabi untuk mensyukuri nikmat itu.<br><br></div>  ",    type: 'info'  });})
document.getElementById("srt-93").innerHTML = ' <a onClick="return noHistory(this);" href="145.html#1">1</a> <a onClick="return noHistory(this);" href="145.html#2">2</a> <a onClick="return noHistory(this);" href="145.html#3">3</a> <a onClick="return noHistory(this);" href="145.html#4">4</a> <a onClick="return noHistory(this);" href="145.html#5">5</a> <a onClick="return noHistory(this);" href="145.html#6">6</a> <a onClick="return noHistory(this);" href="145.html#7">7</a> <a onClick="return noHistory(this);" href="145.html#8">8</a> <a onClick="return noHistory(this);" href="145.html#9">9</a> <a onClick="return noHistory(this);" href="145.html#10">10</a> <a onClick="return noHistory(this);" href="145.html#11">11</a> </br> </br> ';
  